% cd '~/Documents/Work/inner voice/fugues/MIDI'
CMajor1 = readmidi('~/Documents/Work/inner voice/fugues/MIDI/1-1BWV846_C_Major.mid');
CMajor2 = readmidi('~/Documents/Work/inner voice/fugues/MIDI/2-25BWV870_C_Major.mid');
Cminor2 = readmidi('~/Documents/Work/inner voice/fugues/MIDI/2-26BWV871_C_minor.mid');
CshMajor1 = readmidi('~/Documents/Work/inner voice/fugues/MIDI/1-3BWV848_C#_Major.mid');
Cshminor1 = readmidi('~/Documents/Work/inner voice/fugues/MIDI/1-4BWV849_C#_minor.mid');
Dminor1 = readmidi('~/Documents/Work/inner voice/fugues/MIDI/1-6BWV851_D_minor.mid');
Dshminor1 = readmidi('~/Documents/Work/inner voice/fugues/MIDI/1-8BWV853_D#_minor.mid');
EMajor1 = readmidi('~/Documents/Work/inner voice/fugues/MIDI/1-9BWV854_E_Major.mid');
Eminor1 = readmidi('~/Documents/Work/inner voice/fugues/MIDI/1-10BWV855_E_minor.mid');
Fminor1 = readmidi('~/Documents/Work/inner voice/fugues/MIDI/1-11BWV856_F_minor.mid');
GMajor1 = readmidi('~/Documents/Work/inner voice/fugues/MIDI/1-15BWV860_G_Major.mid');
Gminor1 = readmidi('~/Documents/Work/inner voice/fugues/MIDI/1-16BWV861_G_minor.mid');
Aminor1 = readmidi('~/Documents/Work/inner voice/fugues/MIDI/1-20BWV865_A_minor.mid');
Bbmajor1 = readmidi('~/Documents/Work/inner voice/fugues/MIDI/1-21BWV866_Bb_Major.mid');